import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

describe("admin stage8 shell", () => {
  it("exposes the governance route and command helpers", () => {
    const app = readFileSync("apps/admin/src/App.tsx", "utf8");
    const nav = readFileSync("apps/admin/src/stage8-nav.ts", "utf8");
    const api = readFileSync("apps/admin/src/stage8-api.ts", "utf8");
    const stage2Api = readFileSync("apps/admin/src/stage2-api.ts", "utf8");
    const view = readFileSync("apps/admin/src/stage8-views.tsx", "utf8");

    expect(nav).toContain("Governance");
    expect(nav).toContain("/stage8/governance");
    expect(app).toContain("stage8AdminViewDefinitions");
    expect(app).toContain("Stage8GovernanceView");
    expect(app).toContain("/stage8/governance");
    expect(api).toContain("/stage8/governance/overview");
    expect(api).toContain("/stage8/admin-operation-previews");
    expect(api).toContain("stage8AdminCommandCatalog");
    expect(api).toContain("getGovernanceOverview");
    expect(api).toContain("createAdminOperationPreview");
    expect(api).toContain("/stage8/governance-controls");
    expect(api).toContain("/stage8/governance-control-previews");
    expect(api).toContain("listGovernanceControls");
    expect(api).toContain("createGovernanceControlPreview");
    expect(api).toContain("createGovernanceControl");
    expect(api).toContain("liftGovernanceControl");
    expect(api).toContain("pending_review");
    expect(api).toContain("reviewRequestId");
    expect(api).toContain("/stage8/high-risk-governance-reviews");
    expect(api).toContain("listHighRiskGovernanceReviews");
    expect(api).toContain("getHighRiskGovernanceReviewDetail");
    expect(api).toContain("approveHighRiskGovernanceReview");
    expect(api).toContain("rejectHighRiskGovernanceReview");
    expect(api).toContain("withdrawHighRiskGovernanceReview");
    expect(stage2Api).toContain("manage_governance_control");
    expect(view).toContain("createSensitiveOperationChallenge");
    expect(view).toContain("verifySensitiveOperationChallenge");
    expect(view).toContain("governance_control_scope");
    expect(view).toContain("governanceIdempotencyKey");
    expect(view).toContain("liftIdempotencyKey");
    expect(view).toContain("Stage 8 Governance");
    expect(view).toContain("Operation Preview");
    expect(view).toContain("Pilot Metrics");
    expect(view).toContain("Governance Controls");
    expect(view).toContain("Review Requests");
    expect(view).toContain("Refresh Reviews");
    expect(view).toContain("Load Review Detail");
    expect(view).toContain("Create Review Challenge");
    expect(view).toContain("Verify Review Challenge");
    expect(view).toContain("Approve Review");
    expect(view).toContain("Reject Review");
    expect(view).toContain("Withdraw Review");
    expect(view).toContain("Frozen Payload");
    expect(view).toContain("Evidence");
    expect(view).toContain("decisionState");
    expect(view).toContain("executionState");
    expect(view).toContain("reviewRequestId");
    expect(view).toContain("reviewRejectReason");
    expect(view).toContain("reviewWithdrawReason");
    expect(view).toContain("Idempotency Key");
    expect(view).toContain("Create Challenge");
    expect(view).toContain("Verify Challenge");
    expect(view).toContain("Create Control");
    expect(view).toContain("Create Lift Challenge");
    expect(view).toContain("Verify Lift Challenge");
    expect(view).toContain("Lift Control");
  });
});
